1. soru

In [4]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz_notlar = list(set(notlar))
print("benzersiz notlar", benzersiz_notlar)

en_yuksek = max(notlar)
en_dusuk = min(notlar)
print("En yüksek ", en_yuksek)
print("En düşük ", en_dusuk)

sirali_notlar = sorted(notlar)
print("sıralı Notlar", sirali_notlar)

benzersiz notlar [100, 92, 85, 76]
En yüksek  100
En düşük  76
Sıralı Notlar [76, 76, 85, 85, 92, 92, 92, 100]


In [15]:
def armstrong(sayi):
    basamaklar = str(sayi)
    toplam = 0
    for b in basamaklar:
        toplam += int(b) ** 3
    return toplam == sayi

print(armstrong(153))
print(armstrong(444))
print(armstrong(666))
print(armstrong(123))

True
False
False
False


In [6]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
ortak = A & B
print("ortak olanlar", ortak)
sadece_A = A - B
print("sadece a da olanlar", sadece_A)
birlesim = sorted(A | B)
print("alafabetik birleşimleri", birlesim)


ortak olanlar {'SQL', 'Python'}
sadece a da olanlar {'Java', 'R'}
alafabetik birleşimleri ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [7]:
import random
import statistics
sayilar = [random.randint(1, 100) for i in range(10)]
ortalama = statistics.mean(sayilar)
print("ortalama", ortalama)
std_sapma = statistics.stdev(sayilar)
print(std_sapma)

ortalama 43.6
24.985329028585287


In [9]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    counter = {}
    for i in kelimeler:
        if i in counter:
            counter[i] += 1
        else:
            counter[i] = 1


    tekrar = max(counter, key=counter.get)
    return toplam, en_uzun, tekrar


metin = "Elif veri bilimi veri vilimi elif"
print(kelime_sayaci(metin))


(6, 'bilimi', 'veri')


In [12]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
print("çift", ciftler)
kareler = list(map(lambda x: x ** 2, ciftler))
print("kareleri", kareler)
sirali = sorted(kareler, reverse=True)
print("siralanmis" ,sirali)

çift [12, 18, 24, 16]
kareleri [144, 324, 576, 256]
siralanmis [576, 324, 256, 144]


In [13]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
uzunluk= list(map(lambda x: (len(x), x), kelimeler))
sirali = sorted(uzunluk)
sonuc = list(map(lambda x: x[1], sirali))
print(sonuc)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [16]:
def rakamlari_topla(metin):
    toplam = 0
    sayi = ""
    for i in metin:
        if i.isdigit():       #rakam mı kontrolü yapıyor
            sayi += i
        else:
            if sayi != "":
                toplam += int(sayi)
                sayi = ""
    if sayi != "":
        toplam += int(sayi)
    return toplam
metin = "abc12def3"
print(rakamlari_topla(metin))


15


In [17]:
import numpy as np

dizi = np.random.randint(0, 51, 10)

ortalama = np.mean(dizi)
print("ortalama", ortalama)

std_sapma = np.std(dizi)
print("standart sapma:", std_sapma)

en_buyuk = np.max(dizi)
print("En büyük", en_buyuk)

ortalama 24.2
standart sapma: 16.951696080333672
En büyük 48


In [18]:
matris = np.random.rand(5,5)
print("matris\n", matris)

sutun_ort = np.mean(matris, axis=0)
print("sütun ort", sutun_ort)

binary_matris = np.where(matris > 0.5, 1, 0)
print("binary matris\n", binary_matris)

matris
 [[0.53708344 0.52819957 0.70498444 0.63144569 0.87288371]
 [0.56897714 0.62361308 0.96780169 0.84486512 0.9262753 ]
 [0.25981221 0.58306092 0.87332624 0.22339772 0.30901279]
 [0.35640946 0.77120109 0.03304229 0.19129781 0.30623268]
 [0.30328606 0.94031144 0.17296321 0.58810853 0.92829057]]
sütun ort [0.40511366 0.68927722 0.55042357 0.49582297 0.66853901]
binary matris
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [0 1 0 1 1]]
